### PR TITLE
Fix detection of mobile devices

### PR DESCRIPTION
**Pull request by saghul**
Only consider a device is a desktop computer iff is not a mobile nor a
tablet.

### CODE REVIEW

**Comment by saghul** [comment]
Chrome for iPad doesn't set the mobile flag, so !!(!false || !true) == true. Oops!

**Comment by saghul** [comment]
Extra karma if if you can make a quick point release :-)

**Comment by ibc** [comment]
wow, annoying bug!

**Comment by ibc** [comment]
0.6.4 landed.

**Comment by saghul** [comment]
:heart_eyes:

**Pull request merged**
