### PR TITLE
Compatibility with node-webkit applications

### PR DESCRIPTION
**Pull request by adombrovsky**
Currently rtcninja show an error that webrtc is not supported because some variables are not defined correctly

### CODE REVIEW

**Comment by ibc** [comment]
There is no `window` in Node, and `global` becomes `window` when running in a browser.

I cannot add this exception just because node-webkit adds a ugly `global.window` namespace (that's really hateful). In fact, adding `window` to the Node's `global` namespace is 100% undesirable for many reasons.

But I'll make a rtcninja plugin for node-webkit soon.

BTW: does node-webkit pollute the global namespace with `RTCPeerConnection` and so on? or does it expose them as a return value of the module itself within a returned object?

**Comment by ibc** [comment]
Opps, it seems that node-webkit is not a module for Node, but a complete and separate application... so sad.

**Comment by adombrovsky** [comment]
I will be very grateful if you create a plugin for node-webkit

**Comment by jesusprubio** [comment]
I agree with Iñaki, I dislike this "ugly global.window". But after made a research about Node-webkit we've decided to include the support in this same way to keep it simple. I noticed that your source code is outdated so I've added the changes directly in the master branch. Could you please check if this is ok for your case before publishing this new version to the NPM registry? :)

Thanks :)

**Comment by adombrovsky** [comment]
@jesusprubio  i will check it as soon as possible

**Comment by jesusprubio** [comment]
ping? :smile:

**Comment by adombrovsky** [comment]
Hi. Sorry, i didn't have a time to write a response. Everything works well. Thank you for this fix

**Comment by ibc** [comment]
Thanks a lot.

**Pull request closed without merging**
